# Trabajo Practico n4 - Introduccion a numpy.
## Criterios de evaluación.

* Se deben utilizar nombres de variables descriptivos y claros (Utilizar la nomeclatura correspondiente para los nombres de variables).
* Comentarios claros y concisos que expliquen el propósito de cada sección del código.
* Utilizar mensajes de commit **descriptivos**. (Puedes utilizar la extension CONVENTIONAL COMMIT de VS-CODE). 
* Entrega en tiempo y forma.
* Todo el código desarrollado debe ser subido a un repositorio en GitHub (el nombre del repositorio de seguir la siguiente estructura: tp4_tlp3_nombre_apellido).
* Para resolver las actividades se debe insertar casillas de codigo entre cada actividad del cuaderno de Jupyter

### ¡Importante!
**El incumplimiento de los criterios de evaluación restará puntos en la nota final del práctico!**

**Actividad 1:**: Crea un array de NumPy que contenga los números del 0 al 9. (Debes utilizar un metodo de numpy para su creacion.)

In [ ]:
import numpy as np
from random import randint

#todo: 
# crear un array y le ezpecificamos que sea hasta el 9
array_numeros = np.arange(10)
print("Array del 0 al 9:", array_numeros)

Array del 0 al 9: [0 1 2 3 4 5 6 7 8 9]


**Actividad 2:** Crea un array de 5 ceros, y luego cambia el tercer elemento (índice 2) para que sea 5. (Debes utilizar un metodo de numpy para su creacion.)

In [ ]:
#todo:
# crear un array de ceros y le especidicamos cuantas columnas y filas queremos
array_ceros = np.zeros(5)

# decimos que el array de ceros en el indece 2 va ser igual a 5 
array_ceros[2] = 5

print("Array:", array_ceros)

Array: [0. 0. 5. 0. 0.]


**Actividad 3:** Genera una matriz 3x3 de números aleatorios entre 0 y 1.

In [ ]:
#todo:
# esto hace que haga un array de numeros random del 0 al 1 y le especificamos cuantas columnos y filas va tener
matriz_aleatoria = np.random.rand(3, 3)
print("Matriz:\n", matriz_aleatoria)

Matriz:
 [[0.57136076 0.75115066 0.92472883]
 [0.90693707 0.63465769 0.60805448]
 [0.19303972 0.43862389 0.83162308]]


**Actividad 4:** Dado el siguiente array `arr = np.array([10, 20, 30, 40, 50])`
1. Suma 5 a cada elemento.
2. Multiplica todo por un numero aleatorio (utiliza el modulo random para generarlo.)

In [ ]:
#todo:
arr = np.array([10, 20, 30, 40, 50])

# sumamos cada indece el 5
arr_sumado = arr + 5
# genera  un numero aleatorio entre el 2 y el 10
numero_aleatorio = randint(2,10)

# sumamos el array que sumaos con 5 por el numero aleatorio
arr_sumado_multiplicado = arr_sumado * numero_aleatorio
# summos el array normal por el nuemro aleatorio
arr_multiplicado = arr * numero_aleatorio

print("Array original:", arr)
print("Array +5:", arr_sumado)

print(f"Array multiplicado por {numero_aleatorio}:", arr_multiplicado)
print(f"Array que se sumo por {numero_aleatorio}", arr_sumado_multiplicado )

Array original: [10 20 30 40 50]
Array +5: [15 25 35 45 55]
Array multiplicado por 4: [ 40  80 120 160 200]
Array que se sumo por 4 [ 60 100 140 180 220]


**Actividad 5:** Crea una matriz identidad de tamaño 4x4 (unos en la diagonal principal y ceros en el resto).

In [ ]:
#todo:
# el np.eye gener un array identidad y le especificamos de cuantas filas y columnas va ser con un solo numero
matriz_identidad = np.eye(4)
print("Matriz identidad:\n", matriz_identidad)

Matriz identidad:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Actividad 6:** Crea un array que comience en 0 hasta el 20, pero que solo tenga numeros pares yu luego realiza las 4 operaciones basicas. (suma, resta, multiplicacion, division).

In [ ]:
#todo: 
# un array que empieza en 0 termina en 20 y que vaya avanznado de a 2 
arr = np.arange(0,21,2)
print("Array original:", arr)

# suma cada iteracion del array 
suma = arr + 2

# resta cada iteracion del array
resta= arr - 2

# multiplica cada iteracion del array
multiplicacion = arr * 2

# divide cada iteracion del array
division = arr / 2

print("Suma: ", suma)
print("Resta:", resta)
print("Multiplicacion:" , multiplicacion)
print("Division: ", division )


Array original: [ 0  2  4  6  8 10 12 14 16 18 20]
Suma:  [ 2  4  6  8 10 12 14 16 18 20 22]
Resta: [-2  0  2  4  6  8 10 12 14 16 18]
Multiplicacion: [ 0  4  8 12 16 20 24 28 32 36 40]
Division:  [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
